const sequelize = require('sequelize');
const billModel = global.dbObject.define('bills',{
    zp_code:{
        type:sequelize.STRING,
        field:'zp_code',
        allowNull:false,
    },
    gov_code:{
        type:sequelize.STRING,
        field:'gov_code',
        allowNull:false,
    },
    officeid:{
        type:sequelize.INTEGER,
        field:'officeid',
        allowNull:false,
    },
    deptid:{
        type:sequelize.INTEGER,
        field:'deptid',
        allowNull:false,
    },
    name:{
        type:sequelize.STRING,
        field:'name',
        allowNull:false,
    },
    fy:{
        type:sequelize.STRING,
        field:'fy',
        allowNull:false,
    },
    nature:{
        type:sequelize.STRING,
        field:'nature',
        allowNull:false,
    },
    provision:{
        type:sequelize.INTEGER,
        field:'provision',
        allowNull:false,
    },
    pexp:{
        type:sequelize.INTEGER,
        field:'pexp',
        allowNull:false,
    },
    billamt:{
        type:sequelize.INTEGER,
        field:'billamt',
        allowNull:false,
    },
    vno:{
        type:sequelize.INTEGER,
        field:'vno',
        allowNull:false,
    },
    date:{
        type:sequelize.DATE,
        field:'date',
        allowNull:false,
    },
    acceptamt:{
        type:sequelize.INTEGER,
        field:'acceptamt',
        allowNull:false,
    },
    status:{
        type:sequelize.STRING,
        field:'status',
        allowNull:false,
    },
    reason:{
        type:sequelize.STRING,
        field:'reason',
        allowNull:false,
    },
    approved_at:{
        type:sequelize.DATE,
        field:'approved_at',
    },
    created_by:{
        type:sequelize.STRING,
        field:'created_by',
        allowNull:false,
    },
    approved_by:{
        type:sequelize.STRING,
        field:'approved_by',
        allowNull:false,
    },
    
});

module.exports = billModel;
